internal/controller/cluster_controller.go, internal/controller/service_controller.go, pkg/capicluster/cluster.go, pkg/common/common.go, pkg/logged-cluster/interface.go, pkg/logging-reconciler/logging_reconciler.go, pkg/reconciler/interface.go, pkg/resource/promtail-toggle/observability_bundle_configmap.go, pkg/resource/promtail-toggle/reconciler.go, pkg/resource/promtail-wiring/observability_bundle_app.go, pkg/resource/promtail-wiring/reconciler.go, pkg/vintagemc/cluster.go, pkg/vintagewc/cluster.go
Implement a `logged-cluster` interface with 3 implementations:
- capicluster
- vintagewc
- vintagemc
And let's try to keep the minimum amount of code in these, to limit specific code.
=> Implement logged-cluster interface

CHANGELOG.md, cmd/main.go
We need a different set of reconcilers running on vintage and CAPI clusters.
So we'll have a CLI flag to select which mode we want when running the logging-operator.
=> add --vintage toggle

pkg/capicluster/cluster.go, pkg/logged-cluster/interface.go, pkg/resource/promtail-toggle/observability_bundle_configmap.go, pkg/vintagemc/cluster.go, pkg/vintagewc/cluster.go
We should not overwrite user config for WCs, as some customers set some custom ones.
So we decided to go for extra-configs.
But when discussing with @QuentinBisson yesterday, we understood that:
- vintage MCs don't support extraconfig because they're not reconciled by cluster-operator
- for capi clusters we're not sure
So I did this dirty thing that will work at least on vintage.
To be discussed.
=> add support for extravalues where supported

main.go, pkg/resource/grafana-datasource/grafana-loki-datasource.go, pkg/resource/grafana-datasource/reconciler.go, pkg/resource/logging-credentials/logging_operator_secrets.go
Creates the DS for now, with read credentials from the logging-credentials.
Remark: maybe it should reconciliate the secret directly, rather than a cluster?
=> add grafana datasource

main.go, pkg/resource/grafana-datasource/grafana-loki-datasource.go, pkg/resource/grafana-datasource/reconciler.go, pkg/resource/loki-auth/loki-auth.go, pkg/resource/loki-auth/reconciler.go
Creates loki auth config, and trigger recycling of loki-multi-tenant-proxy pods once done.
Relies on #12 for `GetLogin` and `GetPass` functions.
=> create loki-multi-tenant auth

internal/controller/capicluster_controller.go, internal/controller/vintagemc_controller.go, internal/controller/vintagewc_controller.go, main.go, pkg/capicluster/cluster.go, pkg/logged-cluster/interface.go, pkg/logged-cluster/options.go, pkg/resource/promtail-client/promtail-client.go, pkg/resource/promtail-client/reconciler.go, pkg/vintagemc/cluster.go, pkg/vintagewc/cluster.go
Add promtailclient reconciler
Currently missing cluster name detection for vintageMC, only works on `gauss`.
=> promtailclient reconciler

CHANGELOG.md, pkg/resource/logging-credentials/logging_operator_secrets.go, pkg/resource/promtail-wiring/reconciler.go
Ensure we do not delete userconfigs for workload clusters to fix https://github.com/giantswarm/giantswarm/issues/28257
=> fix logging-operator promtail-wiring that deleted WC user configs

CHANGELOG.md, pkg/resource/promtail-config/promtail-config.go
Towards https://github.com/giantswarm/giantswarm/issues/28346
This PR adds lines in the promtail config so that it can retrieve audit logs. Currently testing on a v19.1.0 cluster
=> Add audit logs

CHANGELOG.md, go.mod, go.sum, pkg/vintagewc/cluster.go
Towards https://github.com/giantswarm/roadmap/issues/2834
Only enable logging on WCs >= 19.1.0
The reason is promtail-app does not work on previous cluster versions.
=> don't allow logging on WCs older than 19.1.0

.nancy-ignore, CHANGELOG.md, pkg/resource/logging-credentials/logging_operator_secrets.go, pkg/resource/logging-credentials/reconciler.go, pkg/resource/loki-auth/loki-auth.go, pkg/resource/promtail-client/promtail-client.go
Towards https://github.com/giantswarm/giantswarm/issues/28445
Having per-cluster orgid will help with performance analysis and provide per-cluster rate limiting.
On top of per-cluster orgid, this patch also sets per-cluster user. So we can enforce the org according to the user.
And a dashboard to show the difference:
* yellow: `giantswarm` tenant for all logs
* green: `gauss` tenant
* blue: my test WC's tenant
=> Have per-cluster credentials and orgid.

CHANGELOG.md, go.mod, pkg/common/common.go, pkg/resource/grafana-datasource/grafana-loki-datasource.go, pkg/resource/logging-credentials/logging_operator_secrets.go, pkg/resource/logging-credentials/reconciler.go, pkg/resource/loki-auth/loki-auth.go, pkg/resource/promtail-client/promtail-client.go
Before:
```
data:
gausspassword: [base64 pass]
gaussuser: Z2F1c3M=
readpassword: [base64 pass]
readuser: cmVhZA==
sm2t7password: [base64 pass]
sm2t7user: c20ydDc=
```
After:
```
data:
gauss: [base64 pass structure]
read: [base64 pass structure]
sm2t7: [base64 pass structure]
```
The base64 pass structure is simple (but can be expanded in the future if needed):
```
password: [password]
```
=> change logging-credentials secret format

CHANGELOG.md, pkg/logged-cluster/interface.go
Related to [#inc-2023-11-10-lokiringunealthy-pvc-space-too-low](https://gigantic.slack.com/archives/C064ZHJ25BQ)
Enabling logging by default on all WCs generate too much traffic and loki-write disks get filled up.
We need to tune it better before enabling logging on all WCs.
=> Default logging behavior on WCs reverted to disable

CHANGELOG.md, pkg/resource/promtail-config/promtail-config.go
Towards https://github.com/giantswarm/giantswarm/issues/28841
This PR adds the following labels to the kubernetes audit logs:
- resource: Type of resource concenred by the audit log
- namespace: Namespace of the resource being touched
=> Add kubernetes audit log labels

.circleci/config.yml, CHANGELOG.md
Towards https://github.com/giantswarm/roadmap/issues/2944 and https://github.com/giantswarm/roadmap/issues/2942
Push logging-operator to CAPZ and CAPA collections so we can setup logging on these installs.
=> push to CAPZ and CAPVCD collections

CHANGELOG.md, helm/logging-operator/values.yaml
Towards
- https://github.com/giantswarm/roadmap/issues/3017
This PR replaces any occurrence of `docker.io` in `values.yaml` files with `gsoci.azurecr.io`,
to make the new ACR registry the default one.
=> Configure gsoci.azurecr.io as the registry to use by default

internal/controller/capicluster_controller.go, internal/controller/predicates/predicates.go, internal/controller/vintagemc_controller.go, internal/controller/vintagewc_controller.go
Towards https://github.com/giantswarm/default-apps-aws/pull/378
This PR use controller runtime watches to be able to rerun a reconciliation loop if the observability-bundle app upgrades from a release prior to 1.0.0 to a release greater than 1.0.0 to fix a race condition issues related to the breaking changes in the bundle.
=> Ensure promtail config is reset everytime the observability bundle resource version is updated

CHANGELOG.md, pkg/resource/logging-credentials/logging_operator_secrets.go, pkg/resource/logging-credentials/reconciler.go
Closing https://github.com/giantswarm/giantswarm/issues/29521
This PR does not fail to reconcile if the loki secret is not found hence avoiding a useless error
=> Fix logging-credentials delete reconciler on disabled MCs

CHANGELOG.md, pkg/resource/loki-auth/loki-auth.go, pkg/resource/loki-auth/reconciler.go
Towards https://github.com/giantswarm/giantswarm/issues/29580
This removes the hack we implemented to restart the multi-tenant proxy in favor of a config watcher/reloader in the app itself
=> Remove multi-tenant proxy restart hack

CHANGELOG.md, pkg/common/common.go, pkg/resource/alloy-secret/reconciler.go, pkg/resource/logging-agents-toggle/observability_bundle_configmap.go
Towards: https://github.com/giantswarm/roadmap/issues/3524
The naming style of Alloy app in the observability bundle is wrong as we are using camel case values there.
```
$ k -n=org-giantswarm get cm golem-observability-bundle-logging-extraconfig -oyaml|bl -p
apiVersion: v1
data:
values: |
apps:
alloy-logs:      <--- here
enabled: false
grafanaAgent:
enabled: true
promtail:
enabled: true
kind: ConfigMap
metadata:
name: golem-observability-bundle-logging-extraconfig
namespace: org-giantswarm
```
This PR fixes this issue by renaming alloy-logs to alloyLogs in the observability-bundle config generated by the logging operator.
=> rename alloy-logs to alloyLogs

CHANGELOG.md, pkg/resource/logging-agents-toggle/observability_bundle_configmap.go
Towards: https://github.com/giantswarm/roadmap/issues/3524
Since the renaming of Alloy app from alloy-logs to alloyLogs in v0.7.1 the logging-operator now required observability bundle version v1.5.3 to run Alloy as logging agent.
=> Fix required observability bundle version to run Alloy as logging agent

CHANGELOG.md
Release v0.11.0 was merged with `theo.brigitte@gmail.com` commit message, which did not trigger the release creation. https://github.com/giantswarm/logging-operator/commit/57bfa4d17ba960beb4a17903473216b15058ab18
=> fix v0.11.0 release

CHANGELOG.md, pkg/resource/logging-config/logging-config.go, pkg/resource/logging-config/promtail-logging-config.go, pkg/resource/logging-config/promtail/logging-config.promtail.yaml.template, pkg/resource/logging-config/reconciler.go
Structured metadata was added to promtail 2.9.0 which was added to v20 so we make sure structured_metadata is only used for those versions.
=> fix promtail usage of stuctured-metadata for v19 clusters

CHANGELOG.md, internal/controller/predicates/predicates.go, tests/ats/Pipfile, tests/ats/Pipfile.lock
This PR fixes the current cluster upgrade issues that has been happening in releases since we enabled alloy as our default logging agent.
For context, here is how a cluster upgrade goes:
1. Upgrade Cluster CR
2. All operators act on it including the logging-operator which generates the config for the currently deployed observability version
The issue here is that in when we upgrade capv releases from v28 to v29, we upgrade the observability bundle from a version < 1.5.3 to a version >= 1.5.3 which is when we deploy alloy as our logging agent: https://github.com/giantswarm/logging-operator/blob/1e338f926451a65f456d00cc155366631ffc13d5/pkg/resource/logging-agents-toggle/observability_bundle_configmap.go#L36
As controllers run in parallel, this causes a race condition between the component …
=> force reconciliation whenever the observability-bundle version changes

CHANGELOG.md, pkg/resource/logging-agents-toggle/observability_bundle_configmap.go
Fixes issues when running observability bundle 1.5.3 as it does not support the [new secret configuration mechanism ](https://github.com/giantswarm/alloy-app/blob/main/CHANGELOG.md#040---2024-08-12)added in observability bundle [1.6.0](https://github.com/giantswarm/observability-bundle/blob/main/CHANGELOG.md#160---2024-08-20). This causes clusters with version 1.5.3 and alloy enabled to fail
=> fix failing release upgrades

CHANGELOG.md, helm/logging-operator/templates/deployment.yaml, helm/logging-operator/values.yaml, main.go, pkg/common/common.go
Towards https://github.com/giantswarm/roadmap/issues/3750
Splitting the [huge PR](https://github.com/giantswarm/logging-operator/pull/263) into small ones.
=> add events-logger in main.go and rename imports

CHANGELOG.md, main.go, pkg/resource/agents-toggle/observability_bundle_configmap.go, pkg/resource/agents-toggle/reconciler.go
Towards https://github.com/giantswarm/roadmap/issues/3750
This PR adds the toggle for the events-logger in the observability-bundle configmap.
=> add toggle for events-logger in observability-bundle configmap

CHANGELOG.md, pkg/resource/logging-config/alloy/logging-config.alloy.yaml.template, pkg/resource/logging-config/alloy/test/logging-config.alloy.170_WC.yaml
This fixes the pod logs selectors as they customer WCs pod logs selectors were incorrectly exchanged
=> fix workload cluster pod logs selectors

CHANGELOG.md, pkg/resource/logging-config/alloy/logging.alloy.template, pkg/resource/logging-config/alloy/test/logging-config.alloy.162_MC.yaml, pkg/resource/logging-config/alloy/test/logging-config.alloy.162_WC.yaml, pkg/resource/logging-config/alloy/test/logging-config.alloy.170_MC.yaml, pkg/resource/logging-config/alloy/test/logging-config.alloy.170_WC.yaml, pkg/resource/logging-config/alloy/test/logging-config.alloy.170_WC_default_namespaces_empty.yaml, pkg/resource/logging-config/alloy/test/logging-config.alloy.170_WC_default_namespaces_nil.yaml
Towards: https://github.com/giantswarm/roadmap/issues/3855
This PRs fixes the `job` label in the logs by removing the `job` relabeling rule which make the default job label appear in logs.
The job label will then be shown as `<pod log namespace/<pod log name>`.
=> Fix `job` label in logs

pkg/resource/logging-config/alloy/logging.alloy.template, pkg/resource/logging-config/alloy/test/logging-config.alloy.162_MC.yaml, pkg/resource/logging-config/alloy/test/logging-config.alloy.162_WC.yaml, pkg/resource/logging-config/alloy/test/logging-config.alloy.170_MC.yaml, pkg/resource/logging-config/alloy/test/logging-config.alloy.170_WC.yaml, pkg/resource/logging-config/alloy/test/logging-config.alloy.170_WC_default_namespaces_empty.yaml, pkg/resource/logging-config/alloy/test/logging-config.alloy.170_WC_default_namespaces_nil.yaml
Towards: https://github.com/giantswarm/roadmap/issues/3855
This PR fixes the namespace, pod, and container label shown in logs.
It does so by extracting those values from the `instance` label which is in the form of `<namespace>/<pod>:<container>`.
=> Fix namespace, pod, and container log label

CHANGELOG.md, pkg/resource/logging-config/alloy/logging.alloy.template, pkg/resource/logging-config/alloy/test/logging-config.alloy.170_MC.yaml, pkg/resource/logging-config/alloy/test/logging-config.alloy.170_WC.yaml, pkg/resource/logging-config/alloy/test/logging-config.alloy.170_WC_default_namespaces_empty.yaml, pkg/resource/logging-config/alloy/test/logging-config.alloy.170_WC_default_namespaces_nil.yaml
We discovered there's a bug in alloy 1.5.0 (which is currently included in our latest giantswarm platform releases) that breaks clustering when there is no `selector` or `namespace_selector`.
This config change will work around the bug and ensure clustering works with Alloy-logs.
=> add namespace selector to alloy podlog (workaround for cluster mode)

CHANGELOG.md, helm/logging-operator/values.yaml, main.go
Try to reduce resource usage by disabling helm secrets caching
=> do not cache helm secrets

CHANGELOG.md, pkg/resource/logging-config/alloy/logging-config.alloy.yaml.template, pkg/resource/logging-config/alloy/test/logging-config.alloy.162_MC.yaml, pkg/resource/logging-config/alloy/test/logging-config.alloy.162_WC.yaml, pkg/resource/logging-config/alloy/test/logging-config.alloy.170_MC.yaml, pkg/resource/logging-config/alloy/test/logging-config.alloy.170_WC.yaml, pkg/resource/logging-config/alloy/test/logging-config.alloy.170_WC_custom_tenants.yaml, pkg/resource/logging-config/alloy/test/logging-config.alloy.170_WC_default_namespaces_empty.yaml, pkg/resource/logging-config/alloy/test/logging-config.alloy.170_WC_default_namespaces_nil.yaml
This PR fixes the schema violation because cpu must be set as a string instead of an integer
=> fix alloy-logs schema-violation

CHANGELOG.md, go.mod, go.sum, pkg/common/common.go, pkg/resource/events-logger-secret/grafana-agent-secret.go, pkg/resource/events-logger-secret/reconciler.go, pkg/resource/logging-config/alloy-logging-config.go, pkg/resource/logging-config/alloy/logging-config.alloy.yaml.template, pkg/resource/logging-config/alloy/logging.alloy.template, pkg/resource/logging-config/alloy/test/logging-config.alloy.162_MC.yaml, pkg/resource/logging-config/alloy/test/logging-config.alloy.162_WC.yaml, pkg/resource/logging-config/alloy/test/logging-config.alloy.170_MC.yaml, pkg/resource/logging-config/alloy/test/logging-config.alloy.170_WC.yaml, pkg/resource/logging-config/alloy/test/logging-config.alloy.170_WC_custom_tenants.yaml, pkg/resource/logging-config/alloy/test/logging-config.alloy.170_WC_default_namespaces_empty.yaml, pkg/resource/logging-config/alloy/test/logging-config.alloy.170_WC_default_namespaces_nil.yaml, pkg/resource/logging-secret/alloy-logging-secret.go, pkg/resource/logging-secret/promtail-logging-secret.go, pkg/resource/logging-secret/reconciler.go
Towards https://github.com/giantswarm/roadmap/issues/3986
This pull request introduces changes to support loading prometheus rules in a tenant in the Mimir Ruler from `Workload Clusters` via alloy-logs. It is based on the change introduced in the observability operator in this PR: https://github.com/giantswarm/observability-operator/pull/353
It also adds support for loading prometheus rules in a tenant in the Loki Ruler from `Management Clusters` via alloy-logs. It is based on https://github.com/giantswarm/observability-operator/pull/354.
Now rules will be loaded into the cluster name prefix from both management cluster and workload clusters.
The main differences with the observability operator changes are that:
- `loki.rules.kubernetes` does not currently support extraQueryMatchers but …
=> move log based alerts rule loading from alloy-rules to alloy-logs

CHANGELOG.md, pkg/common/common.go, pkg/resource/events-logger-config/alloy-events-config.go, pkg/resource/events-logger-config/alloy/events-logger.alloy.template, pkg/resource/events-logger-config/alloy/test/events-logger-config.alloy.MC.yaml, pkg/resource/events-logger-config/alloy/test/events-logger-config.alloy.WC.exclude-namespaces.yaml, pkg/resource/events-logger-config/alloy/test/events-logger-config.alloy.WC.include-namespaces.yaml, pkg/resource/events-logger-config/alloy/test/events-logger-config.alloy.WC.yaml, pkg/resource/events-logger-config/grafana-agent-config.go, pkg/resource/events-logger-config/grafana-agent/events-logger.grafanaagent.template, pkg/resource/events-logger-config/grafana-agent/test/events-logger-config.grafanaagent.MC.yaml, pkg/resource/events-logger-config/grafana-agent/test/events-logger-config.grafanaagent.WC.exclude-namespaces.yaml, pkg/resource/events-logger-config/grafana-agent/test/events-logger-config.grafanaagent.WC.include-namespaces.yaml, pkg/resource/events-logger-config/grafana-agent/test/events-logger-config.grafanaagent.WC.yaml, pkg/resource/logging-config/alloy-logging-config.go, pkg/resource/logging-config/alloy/logging.alloy.template, pkg/resource/logging-config/alloy/test/logging-config.alloy.162_MC.yaml, pkg/resource/logging-config/alloy/test/logging-config.alloy.162_WC.yaml, pkg/resource/logging-config/alloy/test/logging-config.alloy.170_MC.yaml, pkg/resource/logging-config/alloy/test/logging-config.alloy.170_WC.yaml, pkg/resource/logging-config/alloy/test/logging-config.alloy.170_WC_custom_tenants.yaml, pkg/resource/logging-config/alloy/test/logging-config.alloy.170_WC_default_namespaces_empty.yaml, pkg/resource/logging-config/alloy/test/logging-config.alloy.170_WC_default_namespaces_nil.yaml, pkg/resource/logging-secret/promtail-logging-secret.go
This pull request introduces changes to improve timeout configurations for `promtail`, `grafana-agent`, `alloy-events` and `alloy-logs` to better support larger installations. The updates include replacing string-based timeout values with `time.Duration` and adding a new `remote_timeout` parameter across multiple configurations and templates. Below is a summary of the most important changes grouped by theme.
=> Increase default loki.write timeouts in all agents

CHANGELOG.md, pkg/common/common.go, pkg/common/observability_bundle.go, pkg/resource/events-logger-config/reconciler.go, pkg/resource/logging-config/reconciler.go
In a recent refactoring, the logging operator was stuck in logging enabled mode and never tried to clean up resources nor it's finalizer when a cluster CR is being deleted.
This is fixing this
=> fix current finalizer left overs
