CHANGELOG.md
cmd/main.go
internal/controller/capicluster_controller.go
internal/controller/vintagemc_controller.go
internal/controller/vintagewc_controller.go
pkg/capicluster/cluster.go
pkg/logged-cluster/interface.go
pkg/logging-reconciler/logging_reconciler.go
pkg/vintagemc/cluster.go
pkg/vintagewc/cluster.go

We have one controller per kind of cluster we want to reconciliate.
BTW, fixed a bug when adding/removing finalizers.

Have 3 controllers: vintagewc, vintagemc and capicluster.

---

cmd/main.go
internal/controller/capicluster_controller.go
internal/controller/vintagemc_controller.go
internal/controller/vintagewc_controller.go
pkg/common/common.go
pkg/logging-reconciler/logging_reconciler.go
pkg/resource/logging-credentials/logging_operator_secrets.go
pkg/resource/logging-credentials/reconciler.go
pkg/resource/promtail-toggle/observability_bundle_configmap.go
pkg/resource/promtail-toggle/reconciler.go
pkg/resource/promtail-wiring/observability_bundle_app.go
pkg/resource/promtail-wiring/reconciler.go

Create a "source of trust" secret containing logging credentials:
- read user
- write user
- read password
- write password
Generates password when they are not set.

Create logging-credentials secret

---

main.go
pkg/capicluster/cluster.go
pkg/common/common.go
pkg/logged-cluster/interface.go
pkg/logged-cluster/options.go
pkg/vintagemc/cluster.go
pkg/vintagewc/cluster.go

New CLI flag to disable logging on all clusters.

setup global logging disable flag

---

CHANGELOG.md
main.go

Commented reconcilers creation for Vintage WC and CAPI clusters - not supported yet.

Commented reconcilers creation for unsupported clusters

---

.circleci/config.yml
CHANGELOG.md

Push to aws-app-catalog so it gets automatically deployed to aws MCs.

push to aws-app-catalog

---

CHANGELOG.md
helm/logging-operator/templates/rbac.yaml

Towards  https://github.com/giantswarm/giantswarm/issues/27528

Fix logging operator rbac

---

CHANGELOG.md
helm/logging-operator/templates/psp.yaml
helm/logging-operator/templates/rbac.yaml
helm/logging-operator/values.schema.json
helm/logging-operator/values.yaml

Towards https://github.com/giantswarm/giantswarm/issues/28337
This PR adds a new switch for PSP disablement to transition to PSS

Disable psp switch

---

CHANGELOG.md
pkg/resource/promtail-config/promtail-config.go

This PR change the name of some of the logs labels so that it becomes easier to navigate through them

refactor logs labels

---

CHANGELOG.md
pkg/resource/promtail-toggle/observability_bundle_configmap.go

PR is needed by https://github.com/giantswarm/observability-bundle/pull/130 towards https://github.com/giantswarm/roadmap/issues/2879

Add support for observability-bundle 1.0.0

---

CHANGELOG.md
pkg/resource/promtail-toggle/observability_bundle_configmap.go

towards those kind of alerts
https://giantswarm.app.opsgenie.com/alert/detail/522f3d01-2d0d-46ad-aeee-ebabdd76e445-1697547685845/details

Revert support for observability-bundle 1.0.0

---

.circleci/config.yml
CHANGELOG.md

Towards https://github.com/giantswarm/roadmap/issues/2937
Let's deploy the logging operator on capa so we can use opsctl deploy :)

Push to capa

---

.circleci/config.yml
CHANGELOG.md
helm/logging-operator/templates/cilium-network-policy.yaml
helm/logging-operator/templates/network-policy.yaml
helm/logging-operator/values.yaml
internal/controller/capicluster_controller.go
pkg/logging-reconciler/logging_reconciler.go

This PR improves the netpol api in the helm chart

improve netpol ui

---

CHANGELOG.md
helm/logging-operator/templates/deployment.yaml

Towards https://github.com/giantswarm/giantswarm/issues/29262
With this patch Prometheus-agent scrapes data from the pod.

Fix podmonitor

---

CHANGELOG.md
internal/controller/capicluster_controller.go
internal/controller/vintagemc_controller.go
internal/controller/vintagewc_controller.go
pkg/common/observability_bundle.go
pkg/logging-reconciler/logging_reconciler.go
pkg/resource/grafana-agent-config/reconciler.go
pkg/resource/grafana-agent-secret/reconciler.go
pkg/resource/logging-agents-toggle/reconciler.go
pkg/resource/logging-credentials/reconciler.go
pkg/resource/promtail-wiring/reconciler.go

Closes https://github.com/giantswarm/giantswarm/issues/29466 and closes https://github.com/giantswarm/giantswarm/issues/29879

support requeueing

---

CHANGELOG.md

Add missing CHANGELOG entry for https://github.com/giantswarm/logging-operator/pull/167

Add changelog entry for #167

---

.ats/main.yaml
.circleci/config.yml
CHANGELOG.md
tests/ats/Pipfile
tests/ats/Pipfile.lock
tests/ats/pytest.ini
tests/ats/test_logging_op.py
tests/test-values.yaml

Towards https://github.com/giantswarm/roadmap/issues/3616
e2e tests will be added in a a separate PR.

add chart testing to ci pipeline

---

CHANGELOG.md

Release was not published because I kept the additional commit message part ... CI is very strict about this.

fix v0.11.1 release

---

CHANGELOG.md
pkg/resource/logging-config/alloy-logging-config.go
pkg/resource/logging-config/alloy/logging-config.alloy.yaml.template

This PR resolves an ongoing incident where alloy-logs pods are not running due to OOMs

enable vpa on alloy-logs

---

CHANGELOG.md
pkg/resource/grafana-agent-config/grafana-agent-config.go
pkg/resource/logging-config/alloy-logging-config.go
pkg/resource/logging-config/alloy/logging-config.alloy.yaml.template
pkg/resource/logging-config/alloy/logging.alloy.template
pkg/resource/logging-config/alloy/test/logging-config.alloy.162_MC.yaml
pkg/resource/logging-config/alloy/test/logging-config.alloy.162_WC.yaml
pkg/resource/logging-config/alloy/test/logging-config.alloy.170_MC.yaml
pkg/resource/logging-config/alloy/test/logging-config.alloy.170_WC.yaml
pkg/resource/logging-config/alloy/test/logging-config.alloy.170_WC_default_namespaces_empty.yaml
pkg/resource/logging-config/alloy/test/logging-config.alloy.170_WC_default_namespaces_nil.yaml

Closes https://github.com/giantswarm/roadmap/issues/3761

Support private cas

---

CHANGELOG.md
pkg/resource/logging-config/alloy-logging-config_test.go

Unit tests were never failing.
This PR fixes this.

fix logging config unit tests

---

CHANGELOG.md
pkg/logged-cluster/capicluster/cluster.go
pkg/logged-cluster/interface.go
pkg/logged-cluster/options.go
pkg/logged-cluster/vintagemc/cluster.go
pkg/logged-cluster/vintagewc/cluster.go

Towards https://github.com/giantswarm/roadmap/issues/3750
Split the [huge PR](https://github.com/giantswarm/logging-operator/pull/263) into smaller ones.

add EventsLogger option in loggedCluster package

---

pkg/resource/agents-toggle/observability_bundle_configmap.go
pkg/resource/agents-toggle/reconciler.go

This PR refactors a bit of the old code to make it easier to read and maintain
To do so, the code extracts semvers into variables, move log and event toggle to separate functions and use controller-runtime util functions

refactor and simplify code

---

CHANGELOG.md

Add missing changelog entry for https://github.com/giantswarm/logging-operator/pull/309

Add changelog entry for #309

---

CHANGELOG.md
pkg/resource/events-logger-config/alloy-events-config.go
pkg/resource/events-logger-config/alloy/events-logger.alloy.template
pkg/resource/events-logger-config/alloy/test/events-logger-config.alloy.MC.yaml
pkg/resource/events-logger-config/alloy/test/events-logger-config.alloy.WC.yaml
pkg/resource/events-logger-config/grafana-agent-config.go
pkg/resource/events-logger-config/grafana-agent/events-logger.grafanaagent.template
pkg/resource/events-logger-config/grafana-agent/test/events-logger-config.grafanaagent.MC.yaml
pkg/resource/events-logger-config/grafana-agent/test/events-logger-config.grafanaagent.WC.yaml

collect cluster wide events in default namespace

---

internal/controller/capicluster_controller.go
internal/controller/grafana_organization_reconciler.go
internal/controller/vintagemc_controller.go
internal/controller/vintagewc_controller.go
pkg/common/common.go
pkg/logged-cluster/capicluster/cluster.go
pkg/logged-cluster/vintagewc/cluster.go
pkg/resource/agents-toggle/reconciler.go
pkg/resource/events-logger-config/reconciler.go
pkg/resource/events-logger-secret/reconciler.go
pkg/resource/grafana-datasource/reconciler.go
pkg/resource/logging-config/reconciler.go
pkg/resource/logging-credentials/logging_operator_secrets.go
pkg/resource/logging-credentials/reconciler.go
pkg/resource/logging-secret/reconciler.go
pkg/resource/logging-wiring/reconciler.go
pkg/resource/loki-ingress-auth-secret/reconciler.go
pkg/resource/proxy-auth/reconciler.go

Closes https://github.com/giantswarm/giantswarm/issues/33076

fix golangci v2

---

.github/pull_request_template.md
tests/manual_e2e/README.md

As discussed during today's alerts review, here are some small improvements to PR checklist and testing procedure.

improve tests procedure
